server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    default-property-inclusion: non_null

logging:
  file:
    name: logs/vwt-demo-server.log
    path: logs/